In [1]:
import pandas as pd

In [137]:
df = pd.read_csv('sl.csv', sep=';', names=['Angielski', 'Polski', 'Frequency', 'BadlyAnswer', 'PerfectScore'])
df[['Frequency', 'BadlyAnswer', 'PerfectScore']] = 9, 0, 0
df

,Angielski,Polski,Frequency,BadlyAnswer,PerfectScore
0,gripping,wciągający,9,0,0
1,predictable,przewidywalny,9,0,0
2,touching,wzruszający,9,0,0
3,weak,słaby,9,0,0
4,awesome,niesamowity,9,0,0
...,...,...,...,...,...
77,rough and ready,prowizoryczny,9,0,0
78,now and then,od czasu do czasu,9,0,0
79,to be sick and tired of something,być zmęczonym czymś,9,0,0
80,give and take,pójście na wzajemne ustępstwa,9,0,0
81,to be something through and through,być czymś w każdym calu,9,0,0

In [138]:
df1= pd.read_csv('control_files/Data.csv')
df1

,Unnamed: 0,Angielski,Polski,Frequency,BadlyAnswer,PerfectScore
0,0,peers,rowiesnicy,9,0,0
1,1,releases,wydania,9,2,0
2,2,nastiest,najgorszy,9,1,0
3,3,tend,mieć skłonności,9,1,0
4,4,wholesale,hurt,9,1,0
...,...,...,...,...,...,...
2512,2512,to cost an arm and a leg,kosztować krocie,9,0,0
2513,2513,to be a pain in the neck,być nie do zniesienia,9,0,0
2514,2514,to have a big mouth,być plotkarzem,9,0,0
2515,2515,to see eye to eye on sth,być zgodnym co do czegoś,9,0,0
2516,2516,to turn a blind eye to sth,przymykać oko/zignorować,9,0,0

In [139]:
df2 = pd.concat([df1, df]).reset_index().drop(['Unnamed: 0', 'index'], axis=1)
df2

,Angielski,Polski,Frequency,BadlyAnswer,PerfectScore
0,peers,rowiesnicy,9,0,0
1,releases,wydania,9,2,0
2,nastiest,najgorszy,9,1,0
3,tend,mieć skłonności,9,1,0
4,wholesale,hurt,9,1,0
...,...,...,...,...,...
2594,rough and ready,prowizoryczny,9,0,0
2595,now and then,od czasu do czasu,9,0,0
2596,to be sick and tired of something,być zmęczonym czymś,9,0,0
2597,give and take,pójście na wzajemne ustępstwa,9,0,0
2598,to be something through and through,być czymś w każdym calu,9,0,0

In [140]:
df2.to_csv('control_files/Data.csv')

In [141]:
df2

,Angielski,Polski,Frequency,BadlyAnswer,PerfectScore
0,peers,rowiesnicy,9,0,0
1,releases,wydania,9,2,0
2,nastiest,najgorszy,9,1,0
3,tend,mieć skłonności,9,1,0
4,wholesale,hurt,9,1,0
...,...,...,...,...,...
2594,rough and ready,prowizoryczny,9,0,0
2595,now and then,od czasu do czasu,9,0,0
2596,to be sick and tired of something,być zmęczonym czymś,9,0,0
2597,give and take,pójście na wzajemne ustępstwa,9,0,0
2598,to be something through and through,być czymś w każdym calu,9,0,0